apiVersion: v1
kind: Config
current-context: uk-south--a896778
clusters:
  - name: uk-south--a896778
    cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQWsrZ0F3SUJBZ0lSQUt3bWpnd1VwQTQ5Rkw2Mkp3Zm56Y2d3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpVd09USXpNVE15TlRReldoY05NelV3T1RJek1UTXlOalF6V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FhSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBTVliCk5pMmg2WVpUZjZyWlB3a0FIbmFLR1RReVU4Uk40NzFxOVhnTzFLcHM5K2pWVGRoTVVsTzd5U2hGRGM3dExIYkUKL2NPa3hYdTZYSFRSamR6SkttVUhVZDNwM2Y1K2NoMGw2b0p4YnRiZFByT1A1VSt6endTM2g4U1lVbU9vM0g1NwplQlk2TUIxVlRWSUxGSzM3KzE5V3dlbDZ4cTJ1TWdBTWVnYWhKaUNXVWtIdmJJRWtvN255SGUvLzIwUW4zVExuCmhtSExBZVNBQXEwbWZ6YlVkV1I3NU9xVzZNNUk1bHI2NHRxdzZDVmlvUGtiRGpBTUlDcWpMMlIrclVaMXNWQlQKMmhQT3FsSWRtV0l0U2hoUjIrVmtmR2s0T2FjeDFhWlYxeWNveTJIYngzY1BMaXNsWDFZMXprMGNBTThuc1cyego5cTBZNmZqeVpXd3FrMklrK0srSVNlSitNbDBSNTdQNXdQZmlFNlZkRjk5YWJtRFUzZjZyYUlSaDZidVRuSFlPClVKZHZHdUs3dTd0ZFRPQXQxVUV1UjBmRmdSZjRIZ296ejY4OXltWUN1Z0FtY095b1dkQnR0eTBieWt6QXdKUWIKQUtKcE5NVXhRYURpQkhkK1piSzJPbHhBdCttTzNxZkJMaWttRDZxNnJrTXNXUEF5WWlVSSt1TW9PRE1KUVFJRApBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVPRmFKNU5ZazhQSmhiUVU1bTdhWC9nSUR1T013RFFZSktvWklodmNOQVFFTEJRQURnZ0dCQU1DZkxnZzQKRTF6bmN5OFBYcFZDNHNxK3BWNEFBY1pRRElncHZDbVBSajdxdkd5eUVaUEQ5bUVFa2toanNPMDNPamVhZlBUUwpnaUYwcEMvenFZZGNGZ2dZNFdrb1lxaTdNYWZCNEV2WWhTZlhIbndDcWc2eHZ6ZmdteWF1Nks0dm56RXlnVGtNCmJhV0hrRWMvRm5pc1Z5aUM2YzNFamgwTEoxV1N1WVFYRkpGOVo3OGFNU292R2RTRE5pcERGVDdEWFNGdjVjZFYKNTFTOUNBMDdHS29XTGVKenhiMllJcmEwd1IweEY2eE4ydDM2R3ljdUo5N3hpS3RIWlJGMnQ2ay8rVjZtTnB5aQo4WklSZnRwMjVwWHg4aldIR1lMQmNqVEtLVWJHRUxyejVrd1BiYndGS2JuM1ZHU01KMm1KaEZjd0xJR3dlVVpNCkhqZmFnazIxTkZ0SnUvTU03clZZYjJIVWdRdGpaTHFwMGdpV1VIcWYyMXlUQ3hKRzEvY3VMNHVYSlR6aWJuKzAKbFZYVUFMbittZFVaTmoyaVlnaEFSRzNTQStPTjRjL1VqVTFzREg5Zm1NWnJVYjVJL1hLaEFFb2VpcENvbXFYOAo3QTgxdytpK3JJY2ovNzZqWjdXei9BQU9PT2pjUzZVUnRRY0tSellIckRlZlVGdVJXUEVxWkRXTmxBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://api.a896778.kyma.ondemand.com
contexts:
  - name: uk-south--a896778
    context:
      cluster: uk-south--a896778
      user: uk-south--a896778
users:
  - name: uk-south--a896778
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - '--oidc-issuer-url=https://anuk8cmfw.accounts.ondemand.com'
          - '--oidc-client-id=1273b5f8-6dd1-4c94-a9f8-8b1b652e47fb'
          - '--oidc-extra-scope=email'
          - '--oidc-extra-scope=openid'
        command: kubectl-oidc_login
        installHint: |
          kubelogin plugin is required to proceed with authentication
          # Homebrew (macOS and Linux)
          brew install int128/kubelogin/kubelogin

          # Krew (macOS, Linux, Windows and ARM)
          kubectl krew install oidc-login

          # Chocolatey (Windows)
          choco install kubelogin
