apiVersion: v1
kind: Config
current-context: us-east--ca15e0c
clusters:
  - name: us-east--ca15e0c
    cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1akNDQWs2Z0F3SUJBZ0lRTDkzRW45WGtQd2d0YW1jYmsrK3VmVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TlRBNE1UVXhNakl3TkRkYUZ3MHpOVEE0TVRVeE1qSXhORGRhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQm9qQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FZOEFNSUlCaWdLQ0FZRUFwWEg4ClJSQlFsSUVmbGpWWVRUemdoZ0Z5UURwTjlUTnpOL2RGeGxDWk1VUWthS1FTZFByWEtGTXR2QlRRa0lnb0VvOVYKdXBZNU9WTkNDT0h1T3UvMWZwRkVwS1ZHQUJ6c3ZsSFVpQjhUZ09hcVR4OXQ4UkxTRkRxaGF3anZBWVBTQ1U4ZgpoN3NpOEUyVzBqT0E0MVhJUG9zWXN4K1BSekFVQnNSZURQT2huU3R6amdXWVhJbDc3WTZMNk1mNk0vSlpNeFFnCkdlZDFhMGtJWDI5d3J0cWJ6bnB0WmZPSHhkN0tmT0xCM0JLZzNUckVsME52QjNOMFVLV1ZpaUwwSjZrcmpsRmIKbEh3RUJxejJ0UlFJR08remZhdE9KdXJmcklST04wR21LYWttVEFzalNqei9KMW9SeVJzTHZoT0w5c3VTT0UrSApMcDNmZXdWNmkrZGgvT0Erc2tMMXRBWWdFWTVwbGV4cXVXVklvbGV2OURsSDBsTWxpMUpEY3hyUUtTclZrRy9hClY3bThWTjg4SWNBWmMrVTQwMmZKYytDUlFvQzh0c1VjWnY2TDk1K2pvL0VLQTQ3ZVJXdEp5czdkaGlNd2QzMmoKalZsaEw0anFVdDVCQnlPbUEvbnc2Vk9qdnU2R0lUNzlsTjBBZzB4dDJKdmpQWDJpL0Z2U2NyNHgrMG1IQWdNQgpBQUdqUWpCQU1BNEdBMVVkRHdFQi93UUVBd0lCcGpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXCkJCUkxtNTVDK1VvVG9sSit1UGFLdWxMTjVsT3VzekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBWUVBVjNtVXhVTkQKRDhkdHV3Mmk5UnFLMWRnZUVPK1JzRmdONnp5OWV4QjU3aHRDT0tMVXJZaHBXcVFsWUIzbktaZWJCMEo4b21hdwoyS0E1dGdrUUJNdW1zYkQwVEl3bUNpakNxU0J4TDJBZ2tKbXhnVExWbmdmeW14NURFdVIvaWw2SlJBUC9HZ2NvCndpSnlwSGtHRVFOdTZmRW1CbEZnVlQ3aFdENTVSSFdwSWJTOFhYd1JGTWlDa3E0NU1heVhGeGFBOUdVNFNhcmwKeDhsRXlTem1Ja0RTcm90V0pXM2lwVVZqM0IyR3BxandtdlFuL2Z4V2dadUdvVVd2NEp3Z2FYd2UzL3hOangvNQozMVlqTmZ1NllnejBHeUw4NEgwRlo4Ym5KWmszekNLcGd3L1JwZ2UxSFg1MVE5bnVkMW5SS1hwOThYZ0VnY1ExClJIeG5LU2ZqQUtPbVhmeFltQ1d0aHR6T1dZbldyTWllWWNqbFg1b2VML1h6NW80R2FPRWowUHJ6MWxFcFZvaGIKclU0bkRwV01xQ0xicTlYL3NJTFlGY2o4alduVUYxTUFmbWg4aUJJMEZqbnk3bGU3bkpRazJEd2c1MEY4eDNYUgpROGdKcE9od3NRSUJEOWtwWnNTN1liZU1LeEpHaWtLcGhMd0xQSUlTNmJzQ1BlejRTajFjcjk0cQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      server: https://api.ca15e0c.kyma.ondemand.com
contexts:
  - name: us-east--ca15e0c
    context:
      cluster: us-east--ca15e0c
      user: us-east--ca15e0c
users:
  - name: us-east--ca15e0c
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - '--oidc-issuer-url=https://anuk8cmfw.accounts.ondemand.com'
          - '--oidc-client-id=86ab3594-00a6-43a3-894d-fc44415e740f'
          - '--oidc-extra-scope=email'
          - '--oidc-extra-scope=openid'
        command: kubectl-oidc_login
        installHint: |
          kubelogin plugin is required to proceed with authentication
          # Homebrew (macOS and Linux)
          brew install int128/kubelogin/kubelogin

          # Krew (macOS, Linux, Windows and ARM)
          kubectl krew install oidc-login

          # Chocolatey (Windows)
          choco install kubelogin
