apiVersion: v1
kind: Config
current-context: japan-east--c-99567a9
clusters:
  - name: japan-east--c-99567a9
    cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ1ekNDQWsrZ0F3SUJBZ0lSQU9DemdDNWw0TmRHNUhxSi9ieTJnRGd3RFFZSktvWklodmNOQVFFTEJRQXcKRFRFTE1Ba0dBMVVFQXhNQ1kyRXdIaGNOTWpVd09USXpNakV3TmpNd1doY05NelV3T1RJek1qRXdOek13V2pBTgpNUXN3Q1FZRFZRUURFd0pqWVRDQ0FhSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBTGl2Cmp2Mkt3RklIckRGbC9pQlBFOGVxUDVsZ2dEdHJ3bUtHUFQyTVNEaTBDWnhjUVFwbVpseUs1ZlREQzVrUmdQYVMKUmZJN2hSMVNCVW5BMmN6ZUxJU0NlTTAwMnI3ZVJyZ0FIUUlYWi85SkR2aDM2OFhJSDdXazdVY1F6TU9DbW13ZwpmNDBLYVNRUGVSN1hmNnhlTGc5SFVGQnNNZ1dDcE1EYmZ2dnE1d2VDdVRnS0d2eTZlVlVQaXBoTGIyMTFpbURFCk5xS1N2RW1JeThPUTdBUWozVzdsNVJvbTFSSVBQUWVHaXBnQ3NaVE1oT2JnYStPYVNzS1pFZlBWQnltWjI1UE0KOW5Nd0RnT25mSzJnMlA3bzQvdEFRdjg3MWU0am5nTUdPVjhncmVoVGdCN3VnVzFsdkRXNTBOU3RDQmxLMjlRTwpwVHdCbXh3R1lMU1VyU0hBWFhoUUNUS1IrcmV3VEJSM3hIMk5uaGl4dFNXdkFOUXAzZDNocjVnSE1ZQVN5M3VvCjRYdFZTRStvTnlyRVV1RGhicVJmK3hyRzlSdndidHNWZkNrMlNKYTEwdGN1R1VaQ1BJc2VXTG9nYzRXRHE3M3cKRDhENUQ3Y1BoYjBrZ1UzbmhWTHphaGhCelUwOWM1LzVnRUNYVC9pQk0wcmZBRytTNUkyQ1g0ZkRvTHFaVHdJRApBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVrQ1VaZjE1RFY4ZkNmUDFMNVhBWXFEa29JY013RFFZSktvWklodmNOQVFFTEJRQURnZ0dCQURxNnRrcm0KblhJU1lvbVhwR1lSRFBrS2x4RVptVVRPQnpCL1lFNXVxMkdVclNwVDdKRkFuZmkrKzhmZDRCaGZPM2pMdmsyZApmL1ExL0dKT1g2aVVTMGJIUnlrNFo0SHZUN1l0bkJ6NkVlWFBBWGMyMmZpUjY3b0ZsdXFoUmRsOXhGdUFaWTlJCnFCem1ZNmVOdXJKcStBL3VLZG1xakFXNTRhTXhZWGtERWFFaEszYVV4Ukx1RkMrdjFEQ2RCbWdGNnJTUnQxZHMKTUtJM1ZzTFRxTG1hU0ZQdURad3lYTDNsY0xtL2F5UWFMNlQ5V25QT1o4MWJBejdwMVBRU004RVZYS1o1UjV2RQpKWUFGWUw4MWN3ZEEwWW4wak5JdHA4ZDNpMm9wenMzMkk2K2F4Sjh0Q1I5amZhTXh2M3p6Z0RxZTJvQ0NQTGZ4Cm04dks3TFFGbXI4SU1GL0kycDhTYVNCeVlpYkI0OVNaQ1hvU3hJYTZqaEFTaEFUZzkvSENReXZ5WkhGUEtwbjEKdVorQzMrVWd3YkhkbXJBYjRQaGNJSHJuclE3T3VJMlc0VUt5TEZvTzNTL3k1eVU5RE9XZmZ6dU1KMXRmaDNjWQplTmNZa1B4R0svUnFpN0h4VUtwWFM5emJIM2pqeWg4aTltRE9xZ1NmTFdKcldUZVBYMndUT3l1UHNRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      server: https://api.c-99567a9.kyma.ondemand.com
contexts:
  - name: japan-east--c-99567a9
    context:
      cluster: japan-east--c-99567a9
      user: japan-east--c-99567a9
users:
  - name: japan-east--c-99567a9
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - get-token
          - '--oidc-issuer-url=https://anuk8cmfw.accounts.ondemand.com'
          - '--oidc-client-id=431434b1-2da4-41d8-ae61-51d535878c20'
          - '--oidc-extra-scope=email'
          - '--oidc-extra-scope=openid'
        command: kubectl-oidc_login
        installHint: |
          kubelogin plugin is required to proceed with authentication
          # Homebrew (macOS and Linux)
          brew install int128/kubelogin/kubelogin

          # Krew (macOS, Linux, Windows and ARM)
          kubectl krew install oidc-login

          # Chocolatey (Windows)
          choco install kubelogin
